# Generated by Django 5.2.3 on 2025-10-31 05:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40, unique=True, verbose_name='clave de sesión')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='dirección IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='user agent')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('last_activity', models.DateTimeField(auto_now=True, verbose_name='última actividad')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active_sessions', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'sesión de usuario',
                'verbose_name_plural': 'sesiones de usuario',
                'ordering': ['-last_activity'],
                'indexes': [models.Index(fields=['user', 'session_key'], name='app_1_users_user_id_1f0a35_idx'), models.Index(fields=['session_key'], name='app_1_users_session_cc08d6_idx')],
            },
        ),
    ]
