[phases.setup]
nixPkgs = ["python313", "postgresql_16", "mysql80", "pkg-config", "gcc", "zlib", "mariadb-connector-c"]

[phases.install]
# Crea entorno virtual y luego instala dependencias en él
cmds = [
  "python -m venv /opt/venv --system-site-packages",
  "/opt/venv/bin/pip install --upgrade pip setuptools wheel",
  "/opt/venv/bin/pip install --no-cache-dir -r requirements.txt"
]

[start]
cmd = "/opt/venv/bin/python manage.py collectstatic --noinput && /opt/venv/bin/python manage.py migrate && /opt/venv/bin/gunicorn proyecto.wsgi:application --workers 3 --bind 0.0.0.0:$PORT --log-file -"
