[phases.setup]
nixPkgs = ["python313", "postgresql_16", "mysql80", "pkg-config", "gcc", "zlib", "mariadb-connector-c"]

[phases.install]
# Calcula CFLAGS/LDFLAGS con pkg-config y luego instala dependencias
cmds = [
  "python -m pip install --upgrade pip",
  "export MYSQLCLIENT_CFLAGS=\"$(pkg-config mysqlclient --cflags || pkg-config mariadb --cflags)\" && export MYSQLCLIENT_LDFLAGS=\"$(pkg-config mysqlclient --libs || pkg-config mariadb --libs)\" && pip install -r requirements.txt"
]

[start]
cmd = "python manage.py collectstatic --noinput && python manage.py makemigrations && python manage.py migrate && gunicorn proyecto.wsgi:application --workers 3 --bind 0.0.0.0:$PORT --log-file -"
