[phases.setup]
nixPkgs = ["python313", "postgresql_16", "mysql80", "pkg-config", "gcc", "zlib", "mariadb-connector-c"]

[phases.install]
# Instala pip usando ensurepip, luego actualiza e instala dependencias
cmds = [
  "python -m ensurepip --upgrade",
  "python -m pip install --upgrade pip setuptools wheel",
  "python -m pip install --no-cache-dir -r requirements.txt"
]

[start]
cmd = "python manage.py collectstatic --noinput && python manage.py migrate && gunicorn proyecto.wsgi:application --workers 3 --bind 0.0.0.0:$PORT --log-file -"
