[phases.setup]
nixPkgs = ["python313", "postgresql_16", "mysql80", "pkg-config", "gcc", "zlib"]

[phases.install]
cmds = [
    "python -m venv --copies /opt/venv",
    ". /opt/venv/bin/activate",
    "pip install --upgrade pip setuptools wheel",
    "pip install -r requirements.txt"
]

[start]
cmd = "python3 manage.py collectstatic --noinput && python3 manage.py makemigrations && python3 manage.py migrate && gunicorn proyecto.wsgi:application --workers 3 --bind 0.0.0.0:$PORT --log-file -"
